export const CARD_TYPE = {
  NORMAL_MONSTER: 'Normal Monster',
  EFFECT_MONSTER: 'Effect Monster',
  SYNCHRO_MONSTER: 'Synchro Monster',
  SYNCHRO_PENDULUM_EFFECT_MONSTER: 'Synchro Pendulum Effect Monster',
  SYNCHRO_TUNER_MONSTER: 'Synchro Tuner Monster',
  FUSION_MONSTER: 'Fusion Monster',
  XYZ_MONSTER: 'Xyz Monster',
  XYZ_PENDULUM_EFFECT_MONSTER: 'Xyz Pendulum Effect Monster',
  RITUAL_EFFECT_MONSTER: 'Ritual EFfect Monster',
  RITUAL_MONSTER: 'Ritual Monster',
  PENDEULUM_NORMAL_MONSTER: 'Pendulum Normal Monster',
  FLIP_EFFECT_MONSTER: 'Flip Effect Monster',
  FLIP_TUNER_EFFECT_MONSTER: 'Flip Tuner Effect Monster',
  GEMINI_MONSTER: 'Gemini Monster',
  NORMAL_TUNER_MONSTER: 'Normal Tuner Monster',
  PENDULUM_EFFECT_MONSTER: 'Pendulum Effect Monster',
  PENDULUM_EFFECT_RITUAL_MONSTER: 'Pendulum Effect Ritual Monster',
  PENDULUM_FLIP_EFFECT_MONSTER: 'Pendulum Flip Effect Monster',
  PENDULUM_TUNER_EFFECT_MONSTER: 'Pendulum Tuner Effect Monster',
  PENDULUM_EFFECT_FUSION_MONSTER: 'Pendulum Effect Fusion Monster',
  SPIRT_MONSTER: 'Spirit Monster',
  TOON_MONSTER: 'Toon Monster',
  TUNNER_MONSTER: 'Tunner Monster',
  UNION_EFFECT_MONSTER: 'Union Effect Monster',
  LINK_MONSTER: 'Link Monster',
  SPELL_CARD: 'Spell Card',
  TRAP_CARD: 'Trap Card',
  SKILL_CARD: 'Skill Card',
  TOKEN: 'Token',
};

export const FRAME_CARD = {
  NORMAL: 'normal',
  EFFECT: 'effect',
  RITUAL: 'ritual',
  FUSION: 'fusion',
  SYNCHRO: 'synchro',
  XYZ: 'xyz',
  LINK: 'link',
  NORMAL_PENDULUM: 'normal_pendulum',
  EFFECT_PENDULUM: 'effect_pendulum',
  RITUAL_PENMDULUM: 'ritual_pendulum',
  FUSION_PENDULUM: 'fusion_pendulum',
  SYNCHRO_PENDULUM: 'synchro_pendulum',
  XYZ_PENDULUM: 'xyz_pendulum',
  SPELL: 'spell',
  TRAP: 'trap',
  TOKEN: 'token',
  SKILL: 'skill',
};

export const RACE_CARD = {
  AQUA: 'Aqua',
  BEAST: 'Beast',
  BEAST_WARRIOR: 'Beast Warrior',
  CREATOR_GOD: 'Creator God',
  CYBERSE: 'Cyberse',
  DINOSAUR: 'Dinosaur',
  DIVINE_BEAST: 'Divine-Beast',
  DRAGON: 'Dragon',
  FAIRY: 'Fairy',
  FIEND: 'Fiend',
  FISH: 'Fish',
  ILLUSION: 'Illusion',
  INSECT: 'Insect',
  MACHINE: 'Machine',
  PLANT: 'Plant',
  PSYCHIC: 'Pyschic',
  PYRO: 'Pyro',
  REPTILE: 'Reptile',
  SPEELCASTER: 'Spellcaster',
  SEA_SERPENT: 'Sea Serpent',
  THUNDER: 'Thunder',
  WINGED_BEAST: 'Winged Beast',
  WYRM: 'Wyrm',
  ZOMBIE: 'Zombie',
  WARRIOR: 'Warrior',
  NORMAL: 'Normal',
  CONTINUOUS: 'Continuous',
  EQUIP: 'Equip',
  QUICK_PLAY: 'Quick-Play',
  FIELD: 'Field',
  RITUAL: 'Ritual',
};

export const ATTRBUTE_CARD = {
  DARK: 'Dark',
  DIVINE: 'Divene',
  EARTH: 'Earth',
  FIRE: 'Fire',
  LIGHT: 'Light',
  WATER: 'Water',
  WIND: 'Wind',
};
